### ISSUE TITLE
No JSON returned

### ISSUE THREAD

**Issue by syardumi** [jameskang410/scraping-netflix#2]
It seems that the 8 alphanumeric character hex string "c88e2062" changes over time (possibly as a commit or release code?), so the JSON GETs no longer work in the initialize() method. 404 errors are returned by the HTTP requests. How did you determine the URL to hit for getting the JSON?

I did only test in-browser and not via the Python program, though.

**Comment by syardumi** [comment]
I was just able to find the the c88e2062 is a build identifier. The current one is 72729320, but does not work either, though I'm now not sure why not.

https://www.netflix.com/api/shakti/72729320/wigenre?genreId=83&full=false&from=0&to=10000

**Comment by jameskang410** [comment]
yeah you're right. i've been manually going into netflix and figuring out
the key based on API calls that are sent. i'll try to think of a way to
automate all of this.

**Comment by ghost** [comment]
Is there a working build identifier I can use to get the JSON data?

**Comment by jameskang410** [comment]
Sorry guys, officially stumped on this one.
