### ISSUE TITLE
Fan

### ISSUE THREAD

**Issue by Gh0stWires** [jameskang410/scraping-netflix#3]
You have no email so this is my only way of contacting you. I wrote a scraper similar to this......I din't make an api out of it but it did the trick. It worked right up until netflix started using react text on there site. I'm really curious to figure out how you got around this. Because I've been trying to figure it out for awhile. I've thought about using browser automation. but that feels like over kill.

**Comment by jameskang410** [comment]
Haha yeah browser automation would be overkill, but alas, I dont' think I'll have the time to actually fix this. Kind of a dead project at this point.
