### ISSUE TITLE
AJAX URL Changed

### ISSUE THREAD

**Issue by crobertsbmw** [jameskang410/scraping-netflix#4]
This looks awesome by the way. Thanks for making it.
I tried running it and am getting this error:
`Error: Was not able to download JSON data. AJAX URLs may have changed or Netflix ID may be incorrect.`
I tried both the NetflixId cookie and the SecureNetflixId cookie, and neither seemed to work. I opened up netflix and clicked on `browse` and then selected anime, and the Chrome Network tab had this as the URL:
`https://www.netflix.com/api/shakti/113b89c9/pathEvaluator?withSize=true&materialize=true&model=harris` which is similar but not that similar to the URL in the code:
`http://www.netflix.com/api/shakti/c88e2062/wigenre?genreId=%s&full=false&from=0&to=10000`

Is this something you are willing to fix?

**Comment by jameskang410** [comment]
Yeah sorry don't think I'll have enough time to snoop around and make changes. Ever since they went to React, I'm sure they changed some things.
